name: Deploy Next.js App to Azure App Service

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗️ Build Next.js App
        run: npm run build

      - name: 📦 Archive files
        run: |
          zip -r build.zip . -x '*.git*'

      - name: 🚀 Deploy to Azure Web App via Zip
        uses: azure/webapps-deploy@v2
        with:
          app-name: PhotoShareNext
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build.zip
